#:schema https://fastly.jsdelivr.net/gh/jdx/mise@main/schema/mise.json

[settings.node]
mirror_url = "https://npmmirror.com/mirrors/node"

[env]
NPM_REGISTRY ="https://registry.npmmirror.com"

[settings.status]
show_env = true
show_tools = true
